# MySQL Database Configuration
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/student_db?useSSL=false&serverTimezone=UTC
jdbc.username=root
jdbc.password=H@r$hA#0812*2006!
